stages:
  data_ingestion:
    cmd: python wine_quality/components/data_ingestion.py
    deps:
    - wine_quality/components/data_ingestion.py
    outs:
    - artifacts/data_ingestion



  data_validation:
    cmd: python wine_quality/components/data_validation.py
    deps:
    - artifacts/data_ingestion
    - wine_quality/components/data_validation.py
    outs:
    - artifacts/data_validation



  data_transformation:
    cmd: python wine_quality/components/data_transformation.py
    deps:
    - artifacts/data_validation
    - wine_quality/components/data_transformation.py
    outs:
    - artifacts/data_transformation



  model_trainer:
    cmd: python wine_quality/components/model_trainer.py
    deps:
    - artifacts/data_transformation
    - wine_quality/components/model_trainer.py
    outs:
    - artifacts/model_trainer


    
  model_evaluation:
    cmd: python wine_quality/components/model_evaluation.py
    deps:
    - artifacts/model_trainer
    - wine_quality/components/model_evaluation.py
    outs:
    - artifacts/model_evaluation
